/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'region' : Region,
  'status' : ContentStatus,
  'title' : string,
  'content' : string,
  'contentType' : [] | [ContentType],
  'createdAt' : TimeValue,
  'createdBy' : Principal,
  'hidden' : boolean,
  'author' : string,
  'category' : Category,
}
export interface Bike {
  'id' : bigint,
  'region' : Region,
  'colorOptions' : Array<ColorOption>,
  'name' : string,
  'createdBy' : Principal,
  'mainImages' : Array<ImageType>,
  'priceRange' : PriceRange,
  'specs' : string,
  'details' : string,
  'brand' : string,
  'brandLogo' : [] | [ImageType],
}
export interface BrandLogo {
  'logos' : Array<[string, ImageType]>,
  'brandName' : string,
}
export type Category = { 'reviews' : null } |
  { 'comparisons' : null } |
  { 'news' : null } |
  { 'concepts' : null } |
  { 'racing' : null } |
  { 'electric' : null } |
  { 'buyingGuides' : null };
export interface ColorOption {
  'colorCode' : string,
  'name' : string,
  'images' : Array<ImageType>,
}
export interface Comment {
  'id' : bigint,
  'content' : string,
  'createdAt' : TimeValue,
  'hidden' : boolean,
  'author' : Principal,
  'reviewId' : bigint,
}
export type ContentStatus = { 'published' : null } |
  { 'draft' : null };
export type ContentType = { 'review' : null } |
  { 'news' : null };
export type ExternalBlob = Uint8Array;
export type ImageType = { 'uploaded' : ExternalBlob } |
  { 'linked' : string };
export interface PriceRange { 'max' : bigint, 'min' : bigint }
export interface Rating {
  'createdAt' : TimeValue,
  'user' : Principal,
  'rating' : number,
  'reviewId' : bigint,
}
export type Region = { 'usa' : null } |
  { 'europe' : null } |
  { 'asia' : null } |
  { 'middleEast' : null };
export interface Review {
  'id' : bigint,
  'region' : Region,
  'status' : ContentStatus,
  'title' : string,
  'content' : string,
  'contentType' : [] | [ContentType],
  'cons' : Array<string>,
  'createdAt' : TimeValue,
  'createdBy' : Principal,
  'pros' : Array<string>,
  'hidden' : boolean,
  'author' : string,
  'score' : Score,
  'rating' : number,
  'bikeId' : bigint,
}
export interface Score {
  'value' : number,
  'design' : number,
  'comfort' : number,
  'performance' : number,
}
export type TimeValue = bigint;
export interface UserProfile { 'bio' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBike' : ActorMethod<
    [
      string,
      string,
      string,
      PriceRange,
      Array<ImageType>,
      string,
      Region,
      Array<ColorOption>,
      [] | [ImageType],
    ],
    bigint
  >,
  'createComment' : ActorMethod<[bigint, string], bigint>,
  'createOrSaveArticle' : ActorMethod<
    [
      string,
      string,
      string,
      Category,
      Region,
      ContentStatus,
      [] | [ContentType],
    ],
    bigint
  >,
  'createOrSaveReview' : ActorMethod<
    [
      string,
      string,
      string,
      Score,
      bigint,
      Region,
      ContentStatus,
      [] | [ContentType],
      Array<string>,
      Array<string>,
      number,
    ],
    bigint
  >,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteBike' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'editBike' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      PriceRange,
      Array<ImageType>,
      string,
      Region,
      Array<ColorOption>,
      [] | [ImageType],
    ],
    undefined
  >,
  'getAllBikes' : ActorMethod<[], Array<Bike>>,
  'getAllPublishedArticles' : ActorMethod<[], Array<Article>>,
  'getAllPublishedReviews' : ActorMethod<[], Array<Review>>,
  'getBikeById' : ActorMethod<[bigint], [] | [Bike]>,
  'getBrandLogos' : ActorMethod<[], Array<BrandLogo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByReview' : ActorMethod<[bigint], Array<Comment>>,
  'getMyDraftArticles' : ActorMethod<[], Array<Article>>,
  'getMyDraftReviews' : ActorMethod<[], Array<Review>>,
  'getReviewRatings' : ActorMethod<[bigint], Array<Rating>>,
  'getUserBikes' : ActorMethod<[], Array<Bike>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hideArticle' : ActorMethod<[bigint], undefined>,
  'hideComment' : ActorMethod<[bigint], undefined>,
  'hideReview' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishArticle' : ActorMethod<[bigint], undefined>,
  'publishReview' : ActorMethod<[bigint], undefined>,
  'rateReview' : ActorMethod<[bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedPopularBikeEntries' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];