/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceRange = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageType = IDL.Variant({
  'uploaded' : ExternalBlob,
  'linked' : IDL.Text,
});
export const Region = IDL.Variant({
  'usa' : IDL.Null,
  'europe' : IDL.Null,
  'asia' : IDL.Null,
  'middleEast' : IDL.Null,
});
export const ColorOption = IDL.Record({
  'colorCode' : IDL.Text,
  'name' : IDL.Text,
  'images' : IDL.Vec(ImageType),
});
export const Category = IDL.Variant({
  'reviews' : IDL.Null,
  'comparisons' : IDL.Null,
  'news' : IDL.Null,
  'concepts' : IDL.Null,
  'racing' : IDL.Null,
  'electric' : IDL.Null,
  'buyingGuides' : IDL.Null,
});
export const ContentStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const ContentType = IDL.Variant({
  'review' : IDL.Null,
  'news' : IDL.Null,
});
export const Score = IDL.Record({
  'value' : IDL.Nat8,
  'design' : IDL.Nat8,
  'comfort' : IDL.Nat8,
  'performance' : IDL.Nat8,
});
export const Bike = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'colorOptions' : IDL.Vec(ColorOption),
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'mainImages' : IDL.Vec(ImageType),
  'priceRange' : PriceRange,
  'specs' : IDL.Text,
  'details' : IDL.Text,
  'brand' : IDL.Text,
  'brandLogo' : IDL.Opt(ImageType),
});
export const TimeValue = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : IDL.Opt(ContentType),
  'createdAt' : TimeValue,
  'createdBy' : IDL.Principal,
  'hidden' : IDL.Bool,
  'author' : IDL.Text,
  'category' : Category,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : IDL.Opt(ContentType),
  'cons' : IDL.Vec(IDL.Text),
  'createdAt' : TimeValue,
  'createdBy' : IDL.Principal,
  'pros' : IDL.Vec(IDL.Text),
  'hidden' : IDL.Bool,
  'author' : IDL.Text,
  'score' : Score,
  'rating' : IDL.Nat8,
  'bikeId' : IDL.Nat,
});
export const BrandLogo = IDL.Record({
  'logos' : IDL.Vec(IDL.Tuple(IDL.Text, ImageType)),
  'brandName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : TimeValue,
  'hidden' : IDL.Bool,
  'author' : IDL.Principal,
  'reviewId' : IDL.Nat,
});
export const Rating = IDL.Record({
  'createdAt' : TimeValue,
  'user' : IDL.Principal,
  'rating' : IDL.Nat8,
  'reviewId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBike' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PriceRange,
        IDL.Vec(ImageType),
        IDL.Text,
        Region,
        IDL.Vec(ColorOption),
        IDL.Opt(ImageType),
      ],
      [IDL.Nat],
      [],
    ),
  'createComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createOrSaveArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        Region,
        ContentStatus,
        IDL.Opt(ContentType),
      ],
      [IDL.Nat],
      [],
    ),
  'createOrSaveReview' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Score,
        IDL.Nat,
        Region,
        ContentStatus,
        IDL.Opt(ContentType),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Nat8,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteBike' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'editBike' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PriceRange,
        IDL.Vec(ImageType),
        IDL.Text,
        Region,
        IDL.Vec(ColorOption),
        IDL.Opt(ImageType),
      ],
      [],
      [],
    ),
  'getAllBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
  'getAllPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getBikeById' : IDL.Func([IDL.Nat], [IDL.Opt(Bike)], ['query']),
  'getBrandLogos' : IDL.Func([], [IDL.Vec(BrandLogo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByReview' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getMyDraftArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getMyDraftReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewRatings' : IDL.Func([IDL.Nat], [IDL.Vec(Rating)], ['query']),
  'getUserBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hideArticle' : IDL.Func([IDL.Nat], [], []),
  'hideComment' : IDL.Func([IDL.Nat], [], []),
  'hideReview' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishArticle' : IDL.Func([IDL.Nat], [], []),
  'publishReview' : IDL.Func([IDL.Nat], [], []),
  'rateReview' : IDL.Func([IDL.Nat, IDL.Nat8], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedPopularBikeEntries' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceRange = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageType = IDL.Variant({
    'uploaded' : ExternalBlob,
    'linked' : IDL.Text,
  });
  const Region = IDL.Variant({
    'usa' : IDL.Null,
    'europe' : IDL.Null,
    'asia' : IDL.Null,
    'middleEast' : IDL.Null,
  });
  const ColorOption = IDL.Record({
    'colorCode' : IDL.Text,
    'name' : IDL.Text,
    'images' : IDL.Vec(ImageType),
  });
  const Category = IDL.Variant({
    'reviews' : IDL.Null,
    'comparisons' : IDL.Null,
    'news' : IDL.Null,
    'concepts' : IDL.Null,
    'racing' : IDL.Null,
    'electric' : IDL.Null,
    'buyingGuides' : IDL.Null,
  });
  const ContentStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ContentType = IDL.Variant({ 'review' : IDL.Null, 'news' : IDL.Null });
  const Score = IDL.Record({
    'value' : IDL.Nat8,
    'design' : IDL.Nat8,
    'comfort' : IDL.Nat8,
    'performance' : IDL.Nat8,
  });
  const Bike = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'colorOptions' : IDL.Vec(ColorOption),
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'mainImages' : IDL.Vec(ImageType),
    'priceRange' : PriceRange,
    'specs' : IDL.Text,
    'details' : IDL.Text,
    'brand' : IDL.Text,
    'brandLogo' : IDL.Opt(ImageType),
  });
  const TimeValue = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : IDL.Opt(ContentType),
    'createdAt' : TimeValue,
    'createdBy' : IDL.Principal,
    'hidden' : IDL.Bool,
    'author' : IDL.Text,
    'category' : Category,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : IDL.Opt(ContentType),
    'cons' : IDL.Vec(IDL.Text),
    'createdAt' : TimeValue,
    'createdBy' : IDL.Principal,
    'pros' : IDL.Vec(IDL.Text),
    'hidden' : IDL.Bool,
    'author' : IDL.Text,
    'score' : Score,
    'rating' : IDL.Nat8,
    'bikeId' : IDL.Nat,
  });
  const BrandLogo = IDL.Record({
    'logos' : IDL.Vec(IDL.Tuple(IDL.Text, ImageType)),
    'brandName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : TimeValue,
    'hidden' : IDL.Bool,
    'author' : IDL.Principal,
    'reviewId' : IDL.Nat,
  });
  const Rating = IDL.Record({
    'createdAt' : TimeValue,
    'user' : IDL.Principal,
    'rating' : IDL.Nat8,
    'reviewId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBike' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PriceRange,
          IDL.Vec(ImageType),
          IDL.Text,
          Region,
          IDL.Vec(ColorOption),
          IDL.Opt(ImageType),
        ],
        [IDL.Nat],
        [],
      ),
    'createComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createOrSaveArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          Region,
          ContentStatus,
          IDL.Opt(ContentType),
        ],
        [IDL.Nat],
        [],
      ),
    'createOrSaveReview' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Score,
          IDL.Nat,
          Region,
          ContentStatus,
          IDL.Opt(ContentType),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Nat8,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteBike' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'editBike' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PriceRange,
          IDL.Vec(ImageType),
          IDL.Text,
          Region,
          IDL.Vec(ColorOption),
          IDL.Opt(ImageType),
        ],
        [],
        [],
      ),
    'getAllBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
    'getAllPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getBikeById' : IDL.Func([IDL.Nat], [IDL.Opt(Bike)], ['query']),
    'getBrandLogos' : IDL.Func([], [IDL.Vec(BrandLogo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByReview' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getMyDraftArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getMyDraftReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewRatings' : IDL.Func([IDL.Nat], [IDL.Vec(Rating)], ['query']),
    'getUserBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hideArticle' : IDL.Func([IDL.Nat], [], []),
    'hideComment' : IDL.Func([IDL.Nat], [], []),
    'hideReview' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishArticle' : IDL.Func([IDL.Nat], [], []),
    'publishReview' : IDL.Func([IDL.Nat], [], []),
    'rateReview' : IDL.Func([IDL.Nat, IDL.Nat8], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedPopularBikeEntries' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };