/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Bike {
    id: bigint;
    region: Region;
    colorOptions: Array<ColorOption>;
    name: string;
    createdBy: Principal;
    mainImages: Array<ImageType>;
    priceRange: PriceRange;
    specs: string;
    details: string;
    brand: string;
    brandLogo?: ImageType;
}
export interface Rating {
    createdAt: TimeValue;
    user: Principal;
    rating: number;
    reviewId: bigint;
}
export interface Comment {
    id: bigint;
    content: string;
    createdAt: TimeValue;
    hidden: boolean;
    author: Principal;
    reviewId: bigint;
}
export interface BrandLogo {
    logos: Array<[string, ImageType]>;
    brandName: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type TimeValue = bigint;
export interface Score {
    value: number;
    design: number;
    comfort: number;
    performance: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Article {
    id: bigint;
    region: Region;
    status: ContentStatus;
    title: string;
    content: string;
    createdAt: TimeValue;
    createdBy: Principal;
    hidden: boolean;
    author: string;
    category: Category;
}
export interface ColorOption {
    colorCode: string;
    name: string;
    images: Array<ImageType>;
}
export interface PriceRange {
    max: bigint;
    min: bigint;
}
export type ImageType = {
    __kind__: "uploaded";
    uploaded: ExternalBlob;
} | {
    __kind__: "linked";
    linked: string;
};
export interface Review {
    id: bigint;
    region: Region;
    status: ContentStatus;
    title: string;
    content: string;
    createdAt: TimeValue;
    createdBy: Principal;
    hidden: boolean;
    author: string;
    score: Score;
    bikeId: bigint;
}
export interface UserProfile {
    bio: string;
    name: string;
}
export enum Category {
    reviews = "reviews",
    comparisons = "comparisons",
    news = "news",
    concepts = "concepts",
    racing = "racing",
    electric = "electric",
    buyingGuides = "buyingGuides"
}
export enum ContentStatus {
    published = "published",
    draft = "draft"
}
export enum Region {
    usa = "usa",
    europe = "europe",
    asia = "asia",
    middleEast = "middleEast"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBike(name: string, brand: string, specs: string, priceRange: PriceRange, mainImages: Array<ImageType>, details: string, region: Region, colorOptions: Array<ColorOption>, brandLogo: ImageType | null): Promise<bigint>;
    createComment(reviewId: bigint, content: string): Promise<bigint>;
    createOrSaveArticle(title: string, content: string, author: string, category: Category, region: Region, status: ContentStatus): Promise<bigint>;
    createOrSaveReview(title: string, content: string, author: string, score: Score, bikeId: bigint, region: Region, status: ContentStatus): Promise<bigint>;
    deleteArticle(articleId: bigint): Promise<void>;
    deleteBike(bikeId: bigint): Promise<void>;
    deleteComment(commentId: bigint): Promise<void>;
    deleteReview(reviewId: bigint): Promise<void>;
    editBike(bikeId: bigint, name: string, brand: string, specs: string, priceRange: PriceRange, mainImages: Array<ImageType>, details: string, region: Region, colorOptions: Array<ColorOption>, brandLogo: ImageType | null): Promise<void>;
    getAllBikes(): Promise<Array<Bike>>;
    getAllPublishedArticles(): Promise<Array<Article>>;
    getAllPublishedReviews(): Promise<Array<Review>>;
    getBikeById(bikeId: bigint): Promise<Bike | null>;
    getBrandLogos(): Promise<Array<BrandLogo>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommentsByReview(reviewId: bigint): Promise<Array<Comment>>;
    getMyDraftArticles(): Promise<Array<Article>>;
    getMyDraftReviews(): Promise<Array<Review>>;
    getReviewRatings(reviewId: bigint): Promise<Array<Rating>>;
    getUserBikes(): Promise<Array<Bike>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hideArticle(articleId: bigint): Promise<void>;
    hideComment(commentId: bigint): Promise<void>;
    hideReview(reviewId: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    publishArticle(articleId: bigint): Promise<void>;
    publishReview(reviewId: bigint): Promise<void>;
    rateReview(reviewId: bigint, rating: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedPopularBikeEntries(): Promise<void>;
}
import type { Article as _Article, Bike as _Bike, BrandLogo as _BrandLogo, Category as _Category, ColorOption as _ColorOption, ContentStatus as _ContentStatus, ExternalBlob as _ExternalBlob, ImageType as _ImageType, PriceRange as _PriceRange, Region as _Region, Review as _Review, Score as _Score, TimeValue as _TimeValue, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBike(arg0: string, arg1: string, arg2: string, arg3: PriceRange, arg4: Array<ImageType>, arg5: string, arg6: Region, arg7: Array<ColorOption>, arg8: ImageType | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBike(arg0, arg1, arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_Region_n14(this._uploadFile, this._downloadFile, arg6), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg7), await to_candid_opt_n19(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBike(arg0, arg1, arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_Region_n14(this._uploadFile, this._downloadFile, arg6), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg7), await to_candid_opt_n19(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async createComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1);
            return result;
        }
    }
    async createOrSaveArticle(arg0: string, arg1: string, arg2: string, arg3: Category, arg4: Region, arg5: ContentStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrSaveArticle(arg0, arg1, arg2, to_candid_Category_n20(this._uploadFile, this._downloadFile, arg3), to_candid_Region_n14(this._uploadFile, this._downloadFile, arg4), to_candid_ContentStatus_n22(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrSaveArticle(arg0, arg1, arg2, to_candid_Category_n20(this._uploadFile, this._downloadFile, arg3), to_candid_Region_n14(this._uploadFile, this._downloadFile, arg4), to_candid_ContentStatus_n22(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createOrSaveReview(arg0: string, arg1: string, arg2: string, arg3: Score, arg4: bigint, arg5: Region, arg6: ContentStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrSaveReview(arg0, arg1, arg2, arg3, arg4, to_candid_Region_n14(this._uploadFile, this._downloadFile, arg5), to_candid_ContentStatus_n22(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrSaveReview(arg0, arg1, arg2, arg3, arg4, to_candid_Region_n14(this._uploadFile, this._downloadFile, arg5), to_candid_ContentStatus_n22(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteBike(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBike(arg0);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async editBike(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: PriceRange, arg5: Array<ImageType>, arg6: string, arg7: Region, arg8: Array<ColorOption>, arg9: ImageType | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editBike(arg0, arg1, arg2, arg3, arg4, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_Region_n14(this._uploadFile, this._downloadFile, arg7), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg8), await to_candid_opt_n19(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBike(arg0, arg1, arg2, arg3, arg4, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_Region_n14(this._uploadFile, this._downloadFile, arg7), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg8), await to_candid_opt_n19(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async getAllBikes(): Promise<Array<Bike>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBikes();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBikes();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublishedArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedArticles();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedArticles();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublishedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedReviews();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedReviews();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBikeById(arg0: bigint): Promise<Bike | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBikeById(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBikeById(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBrandLogos(): Promise<Array<BrandLogo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandLogos();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandLogos();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsByReview(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByReview(arg0);
            return result;
        }
    }
    async getMyDraftArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDraftArticles();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDraftArticles();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDraftReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDraftReviews();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDraftReviews();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewRatings(arg0: bigint): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewRatings(arg0);
            return result;
        }
    }
    async getUserBikes(): Promise<Array<Bike>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBikes();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBikes();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async hideArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hideArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideArticle(arg0);
            return result;
        }
    }
    async hideComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hideComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideComment(arg0);
            return result;
        }
    }
    async hideReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hideReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideReview(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishArticle(arg0);
            return result;
        }
    }
    async publishReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishReview(arg0);
            return result;
        }
    }
    async rateReview(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateReview(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedPopularBikeEntries(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedPopularBikeEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedPopularBikeEntries();
            return result;
        }
    }
}
function from_candid_Article_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_Bike_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bike): Promise<Bike> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_BrandLogo_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BrandLogo): Promise<BrandLogo> {
    return await from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_ColorOption_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColorOption): Promise<ColorOption> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ContentStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentStatus): ContentStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ImageType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageType): Promise<ImageType> {
    return await from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Region_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImageType]): Promise<ImageType | null> {
    return value.length === 0 ? null : await from_candid_ImageType_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bike]): Promise<Bike | null> {
    return value.length === 0 ? null : await from_candid_Bike_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _Region;
    colorOptions: Array<_ColorOption>;
    name: string;
    createdBy: Principal;
    mainImages: Array<_ImageType>;
    priceRange: _PriceRange;
    specs: string;
    details: string;
    brand: string;
    brandLogo: [] | [_ImageType];
}): Promise<{
    id: bigint;
    region: Region;
    colorOptions: Array<ColorOption>;
    name: string;
    createdBy: Principal;
    mainImages: Array<ImageType>;
    priceRange: PriceRange;
    specs: string;
    details: string;
    brand: string;
    brandLogo?: ImageType;
}> {
    return {
        id: value.id,
        region: from_candid_Region_n27(_uploadFile, _downloadFile, value.region),
        colorOptions: await from_candid_vec_n29(_uploadFile, _downloadFile, value.colorOptions),
        name: value.name,
        createdBy: value.createdBy,
        mainImages: await from_candid_vec_n32(_uploadFile, _downloadFile, value.mainImages),
        priceRange: value.priceRange,
        specs: value.specs,
        details: value.details,
        brand: value.brand,
        brandLogo: record_opt_to_undefined(await from_candid_opt_n36(_uploadFile, _downloadFile, value.brandLogo))
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorCode: string;
    name: string;
    images: Array<_ImageType>;
}): Promise<{
    colorCode: string;
    name: string;
    images: Array<ImageType>;
}> {
    return {
        colorCode: value.colorCode,
        name: value.name,
        images: await from_candid_vec_n32(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _Region;
    status: _ContentStatus;
    title: string;
    content: string;
    createdAt: _TimeValue;
    createdBy: Principal;
    hidden: boolean;
    author: string;
    category: _Category;
}): {
    id: bigint;
    region: Region;
    status: ContentStatus;
    title: string;
    content: string;
    createdAt: TimeValue;
    createdBy: Principal;
    hidden: boolean;
    author: string;
    category: Category;
} {
    return {
        id: value.id,
        region: from_candid_Region_n27(_uploadFile, _downloadFile, value.region),
        status: from_candid_ContentStatus_n40(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        hidden: value.hidden,
        author: value.author,
        category: from_candid_Category_n42(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _Region;
    status: _ContentStatus;
    title: string;
    content: string;
    createdAt: _TimeValue;
    createdBy: Principal;
    hidden: boolean;
    author: string;
    score: _Score;
    bikeId: bigint;
}): {
    id: bigint;
    region: Region;
    status: ContentStatus;
    title: string;
    content: string;
    createdAt: TimeValue;
    createdBy: Principal;
    hidden: boolean;
    author: string;
    score: Score;
    bikeId: bigint;
} {
    return {
        id: value.id,
        region: from_candid_Region_n27(_uploadFile, _downloadFile, value.region),
        status: from_candid_ContentStatus_n40(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        hidden: value.hidden,
        author: value.author,
        score: value.score,
        bikeId: value.bikeId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logos: Array<[string, _ImageType]>;
    brandName: string;
}): Promise<{
    logos: Array<[string, ImageType]>;
    brandName: string;
}> {
    return {
        logos: await from_candid_vec_n51(_uploadFile, _downloadFile, value.logos),
        brandName: value.brandName
    };
}
async function from_candid_tuple_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ImageType]): Promise<[string, ImageType]> {
    return [
        value[0],
        await from_candid_ImageType_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    usa: null;
} | {
    europe: null;
} | {
    asia: null;
} | {
    middleEast: null;
}): Region {
    return "usa" in value ? Region.usa : "europe" in value ? Region.europe : "asia" in value ? Region.asia : "middleEast" in value ? Region.middleEast : value;
}
async function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uploaded: _ExternalBlob;
} | {
    linked: string;
}): Promise<{
    __kind__: "uploaded";
    uploaded: ExternalBlob;
} | {
    __kind__: "linked";
    linked: string;
}> {
    return "uploaded" in value ? {
        __kind__: "uploaded",
        uploaded: await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.uploaded)
    } : "linked" in value ? {
        __kind__: "linked",
        linked: value.linked
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): ContentStatus {
    return "published" in value ? ContentStatus.published : "draft" in value ? ContentStatus.draft : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reviews: null;
} | {
    comparisons: null;
} | {
    news: null;
} | {
    concepts: null;
} | {
    racing: null;
} | {
    electric: null;
} | {
    buyingGuides: null;
}): Category {
    return "reviews" in value ? Category.reviews : "comparisons" in value ? Category.comparisons : "news" in value ? Category.news : "concepts" in value ? Category.concepts : "racing" in value ? Category.racing : "electric" in value ? Category.electric : "buyingGuides" in value ? Category.buyingGuides : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bike>): Promise<Array<Bike>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Bike_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ColorOption>): Promise<Array<ColorOption>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ColorOption_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImageType>): Promise<Array<ImageType>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ImageType_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n45(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BrandLogo>): Promise<Array<BrandLogo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BrandLogo_n49(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ImageType]>): Promise<Array<[string, ImageType]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n52(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_ColorOption_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorOption): Promise<_ColorOption> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ContentStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): _ContentStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ImageType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageType): Promise<_ImageType> {
    return await to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Region_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageType | null): Promise<[] | [_ImageType]> {
    return value === null ? candid_none() : candid_some(await to_candid_ImageType_n11(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorCode: string;
    name: string;
    images: Array<ImageType>;
}): Promise<{
    colorCode: string;
    name: string;
    images: Array<_ImageType>;
}> {
    return {
        colorCode: value.colorCode,
        name: value.name,
        images: await to_candid_vec_n10(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "uploaded";
    uploaded: ExternalBlob;
} | {
    __kind__: "linked";
    linked: string;
}): Promise<{
    uploaded: _ExternalBlob;
} | {
    linked: string;
}> {
    return value.__kind__ === "uploaded" ? {
        uploaded: await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.uploaded)
    } : value.__kind__ === "linked" ? {
        linked: value.linked
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): {
    usa: null;
} | {
    europe: null;
} | {
    asia: null;
} | {
    middleEast: null;
} {
    return value == Region.usa ? {
        usa: null
    } : value == Region.europe ? {
        europe: null
    } : value == Region.asia ? {
        asia: null
    } : value == Region.middleEast ? {
        middleEast: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    reviews: null;
} | {
    comparisons: null;
} | {
    news: null;
} | {
    concepts: null;
} | {
    racing: null;
} | {
    electric: null;
} | {
    buyingGuides: null;
} {
    return value == Category.reviews ? {
        reviews: null
    } : value == Category.comparisons ? {
        comparisons: null
    } : value == Category.news ? {
        news: null
    } : value == Category.concepts ? {
        concepts: null
    } : value == Category.racing ? {
        racing: null
    } : value == Category.electric ? {
        electric: null
    } : value == Category.buyingGuides ? {
        buyingGuides: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == ContentStatus.published ? {
        published: null
    } : value == ContentStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ImageType>): Promise<Array<_ImageType>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ImageType_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ColorOption>): Promise<Array<_ColorOption>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ColorOption_n17(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
